# Generated by Django 2.2.14 on 2022-03-08 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamplatform',
            old_name='websit',
            new_name='website',
        ),
    ]
